FROM node:20.18.0

# ENVS
ENV DEBIAN_FRONTEND=noninteractive
ENV TZ=America/Mexico_City
ENV LANG=es_MX.UTF-8
ENV LANGUAGE=es_MX:es
ENV LC_ALL=es_MX.UTF-8
ENV APPHOME=/usr/src/app

# DEPENDENCIES
RUN apt-get update && apt-get upgrade -y
RUN apt-get install -y \
    wget unzip poppler-utils cron locales tzdata git neovim curl zsh supervisor htop

# ZSH 
RUN sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
RUN chsh -s $(which zsh)

# LOCALES
RUN echo "es_MX.UTF-8 UTF-8" >> /etc/locale.gen && \
    locale-gen es_MX.UTF-8 && \
    ln -snf /usr/share/zoneinfo/America/Mexico_City /etc/localtime && \
    echo "America/Mexico_City" > /etc/timezone && \
    dpkg-reconfigure -f noninteractive tzdata && \
    apt-get clean

# LOGS
RUN mkdir /usr/src/logs

# SUPERVISOR
COPY supervisord.conf /etc/supervisor/conf.d/supervisord.conf
CMD ["/usr/bin/supervisord"]

# NODE
RUN npm install -g pnpm
WORKDIR $APPHOME
COPY . $APPHOME
RUN pnpm install --force

